# Loading example datasets

**Agenda**

- How do we load datasets?

- Characteristics of standard datasets that come with scikit-learn sklearn.datasets.load_*

- Data Requirements in scikit-learn


---

## How to load internal datasets 
### General dataset API
- Small standard datasets - sklearn.datasets.load_*
- Larger real world datasets - sklearn.datasets.fetch_*
- Generate data - sklearn.datasets.make_*	


### Introducing the iris dataset

![Iris](images/03_iris.png)

- 50 samples of 3 different species of iris (150 samples total)
- Features - 4 numeric measurements: sepal length, sepal width, petal length, petal width

### Machine learning on the iris dataset

- Framed as a **supervised learning** problem: Predict the species of an iris using the measurements
- This is perhaps the best known database to be found in the pattern recognition and machine learning literature.

### Loading the iris dataset into scikit-learn

In [1]:
# import load_iris function from datasets module
from sklearn.datasets import load_iris

In [2]:
# save "bunch" object containing iris dataset and its attributes
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [3]:
# print the iris data
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### Machine learning terminology revised

- Each row is a **sample** 
- Each column is a **feature** 

In [4]:
# print the names of the four features
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
# print integers representing the species of each observation
# target is the species of iris
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [6]:
# print the encoding scheme for species: 0 = setosa, 1 = versicolor, 2 = virginica
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


- Each value we are predicting is the **response** (also known as: target, outcome, label, dependent variable)
- **Classification** is supervised learning in which the response is categorical
- **Regression** is supervised learning in which the response is ordered and continuous

## Requirements for working with data in scikit-learn

1. Features and response are **separate objects**
2. Features and response should be **numeric**
3. Features and response should be **NumPy arrays**
4. Features and response should have **specific shapes**

In [7]:
# check the types of the features and response
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
# check the shape of the features (first dimension = number of observations, second dimensions = number of features)
# number of samples then number of features
print(iris.data.shape)

(150, 4)


In [9]:
# check the shape of the response (single dimension matching the number of observations)
# targe should match the samples
print(iris.target.shape)

(150,)


## Exercise

Load Wine dataset (load_wine) and print 
- data
- names of the features
- types of the features
- shape of the features
- names of the response
- types of the response
- shape of the response

In [10]:
# Load wine dataset
from sklearn.datasets import load_wine

In [11]:
# Print the wine data 
wine = load_wine()
print(wine.data)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [12]:
# Print the names of the features
print(wine.feature_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [25]:
# Print the types of the features
print(type(wine.data))

<class 'numpy.ndarray'>


In [17]:
# Print the shape of the features
print(wine.data.shape)

(178, 13)


In [26]:
# Rrint the names of the response
print(wine.target)
print(wine.target_names)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
['class_0' 'class_1' 'class_2']


In [22]:
# Print the types of the response
print(type(wine.target))

<class 'numpy.ndarray'>


In [23]:
# Print the shape of the response
print(wine.target.shape)

(178,)


## How to load other datasets

In [27]:
import pandas as pd

# read CSV file directly from a URL and save the results
Advertising_data = pd.read_csv('Advertising.csv', index_col=0)

print('Advertising data columns: ',Advertising_data.columns.values)

Advertising data columns:  ['TV' 'radio' 'newspaper' 'sales']


## Note that the first three columns are features and the last is a response

In [33]:
features = ['TV','radio','newspaper']

Advertising_data_features = Advertising_data[features]

# display the first 5 rows
Advertising_data_features.head()

TV  radio  newspaper
1  230.1   37.8       69.2
2   44.5   39.3       45.1
3   17.2   45.9       69.3
4  151.5   41.3       58.5
5  180.8   10.8       58.4

In [34]:
# display the last 5 rows
Advertising_data_features.tail()

TV  radio  newspaper
196   38.2    3.7       13.8
197   94.2    4.9        8.1
198  177.0    9.3        6.4
199  283.6   42.0       66.2
200  232.1    8.6        8.7

In [30]:
# check the shape of the DataFrame (rows, columns)
Advertising_data.shape

(200, 4)

In [35]:
Advertising_data_target = Advertising_data['sales']
Advertising_data_target.head()

1    22.1
2    10.4
3     9.3
4    18.5
5    12.9
Name: sales, dtype: float64

In [36]:
Advertising_data_target.tail()

196     7.6
197     9.7
198    12.8
199    25.5
200    13.4
Name: sales, dtype: float64

In [38]:
Advertising_data_target.shape

(200,)

What are the features?
- **TV:** advertising dollars spent on TV for a single product in a given market (in thousands of dollars)
- **Radio:** advertising dollars spent on Radio
- **Newspaper:** advertising dollars spent on Newspaper

What is the response?
- **Sales:** sales of a single product in a given market (in thousands of items)

What else do we know?
- Because the response variable is continuous, this is a **regression** problem
- There are 200 **observations** (represented by the rows), and each observation is a single market

## Exercise
Load Avocado dataset (avocado.csv) that has the following columns
- Date - The date of the observation
- AveragePrice - the average price of a single avocado
- type - conventional or organic
- year - the year
- Region - the city or region of the observation
- Total Volume - Total number of avocados sold
- 4046 - Total number of avocados with PLU 4046 sold
- 4225 - Total number of avocados with PLU 4225 sold
- 4770 - Total number of avocados with PLU 4770 sold

as Avocado_data and print 
- column names
- first 5 rows
- last 5 rows
- data shape




In [39]:
# Load avocado dataset as Avocado_data
# NOTE that avg price is response, not feature
Avocado_data = pd.read_csv('avocado.csv',index_col=0)

In [40]:
# Print column names
Avocado_data.columns

Index(['Date', 'AveragePrice', 'Total Volume', '4046', '4225', '4770',
       'Total Bags', 'Small Bags', 'Large Bags', 'XLarge Bags', 'type', 'year',
       'region'],
      dtype='object')

In [58]:
#split into features and targets

#feature_cols = ['Date','Total Volume','4046','4225','4770','Total Bags','Small Bags','Large Bags','XLarge Bags','type','year','region']
#avocado_features = Avocado_data[feature_cols]
avocado_features = Avocado_data.drop('AveragePrice',axis=1)

avocado_target = Avocado_data[['AveragePrice']]

In [43]:
# Print first 5 rows
Avocado_data.head()

Date  AveragePrice  Total Volume     4046       4225    4770  \
0  2015-12-27          1.33      64236.62  1036.74   54454.85   48.16   
1  2015-12-20          1.35      54876.98   674.28   44638.81   58.33   
2  2015-12-13          0.93     118220.22   794.70  109149.67  130.50   
3  2015-12-06          1.08      78992.15  1132.00   71976.41   72.58   
4  2015-11-29          1.28      51039.60   941.48   43838.39   75.78   

   Total Bags  Small Bags  Large Bags  XLarge Bags          type  year  region  
0     8696.87     8603.62       93.25          0.0  conventional  2015  Albany  
1     9505.56     9408.07       97.49          0.0  conventional  2015  Albany  
2     8145.35     8042.21      103.14          0.0  conventional  2015  Albany  
3     5811.16     5677.40      133.76          0.0  conventional  2015  Albany  
4     6183.95     5986.26      197.69          0.0  conventional  2015  Albany

In [44]:
# Print last 5 rows
Avocado_data.tail()

Date  AveragePrice  Total Volume     4046     4225    4770  \
7   2018-02-04          1.63      17074.83  2046.96  1529.20    0.00   
8   2018-01-28          1.71      13888.04  1191.70  3431.50    0.00   
9   2018-01-21          1.87      13766.76  1191.92  2452.79  727.94   
10  2018-01-14          1.93      16205.22  1527.63  2981.04  727.01   
11  2018-01-07          1.62      17489.58  2894.77  2356.13  224.53   

    Total Bags  Small Bags  Large Bags  XLarge Bags     type  year  \
7     13498.67    13066.82      431.85          0.0  organic  2018   
8      9264.84     8940.04      324.80          0.0  organic  2018   
9      9394.11     9351.80       42.31          0.0  organic  2018   
10    10969.54    10919.54       50.00          0.0  organic  2018   
11    12014.15    11988.14       26.01          0.0  organic  2018   

              region  
7   WestTexNewMexico  
8   WestTexNewMexico  
9   WestTexNewMexico  
10  WestTexNewMexico  
11  WestTexNewMexico

In [45]:
# Print data shape
Avocado_data.shape

(18249, 13)

In [56]:
avocado_features.columns

Index(['Date', 'Total Volume', '4046', '4225', '4770', 'Total Bags',
       'Small Bags', 'Large Bags', 'XLarge Bags', 'type', 'year', 'region'],
      dtype='object')

In [46]:
avocado_features.head()

Date  Total Volume     4046       4225    4770  Total Bags  \
0  2015-12-27      64236.62  1036.74   54454.85   48.16     8696.87   
1  2015-12-20      54876.98   674.28   44638.81   58.33     9505.56   
2  2015-12-13     118220.22   794.70  109149.67  130.50     8145.35   
3  2015-12-06      78992.15  1132.00   71976.41   72.58     5811.16   
4  2015-11-29      51039.60   941.48   43838.39   75.78     6183.95   

   Small Bags  Large Bags  XLarge Bags          type  year  region  
0     8603.62       93.25          0.0  conventional  2015  Albany  
1     9408.07       97.49          0.0  conventional  2015  Albany  
2     8042.21      103.14          0.0  conventional  2015  Albany  
3     5677.40      133.76          0.0  conventional  2015  Albany  
4     5986.26      197.69          0.0  conventional  2015  Albany

In [59]:
# print last 5 rows of features
avocado_features.tail()

Date  Total Volume     4046     4225    4770  Total Bags  \
7   2018-02-04      17074.83  2046.96  1529.20    0.00    13498.67   
8   2018-01-28      13888.04  1191.70  3431.50    0.00     9264.84   
9   2018-01-21      13766.76  1191.92  2452.79  727.94     9394.11   
10  2018-01-14      16205.22  1527.63  2981.04  727.01    10969.54   
11  2018-01-07      17489.58  2894.77  2356.13  224.53    12014.15   

    Small Bags  Large Bags  XLarge Bags     type  year            region  
7     13066.82      431.85          0.0  organic  2018  WestTexNewMexico  
8      8940.04      324.80          0.0  organic  2018  WestTexNewMexico  
9      9351.80       42.31          0.0  organic  2018  WestTexNewMexico  
10    10919.54       50.00          0.0  organic  2018  WestTexNewMexico  
11    11988.14       26.01          0.0  organic  2018  WestTexNewMexico

In [48]:
# print features shape
avocado_features.shape

(18249, 12)

In [62]:
#print first 5 rows of target
avocado_target.head()

AveragePrice
0          1.33
1          1.35
2          0.93
3          1.08
4          1.28

In [60]:
# print last 5 rows of targe
avocado_target.tail()

AveragePrice
7           1.63
8           1.71
9           1.87
10          1.93
11          1.62

In [61]:
# print target shape
avocado_target.shape

(18249, 1)

In [63]:
avocado_target.columns

Index(['AveragePrice'], dtype='object')