# Preprocessing

**Agenda**

- What is preprocessing and how it is done?

We will learn how to do the following:
1. Train/Test split
2. Normalization/Standardization
3. Label Encoding
4. Handling Missing Data

---


## Preprocessing overview

In simple words, pre-processing refers to the transformations applied to your data before feeding it to the algorithm 

Scikit-learn library has a pre-built functionality under **sklearn.preprocessing** that we will explore in this module

## Train-Test split

Setting portion of data aside - prerequisite for generalization

Different partitions for training and testing - A core practice in machine learning

Scikit-learn has a convenient method to assist in that process:

**train_test_split(sample, response, test_size=0.25, shuffle=True)**

The split size is controlled using the **attribute test_size** 

**Default test_size** - 25% of the dataset size

**Standard practice** - shuffle the dataset before splitting by setting the attribute **shuffle=True**


In [1]:
import numpy
import pandas as pd
import pickle
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
# split in train and test sets
iris = datasets.load_iris()
iris.data.shape

(150, 4)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, shuffle=True)
X_train.shape

(112, 4)

In [4]:
X_test.shape

(38, 4)

In [5]:
y_train.shape

(112,)

In [6]:
y_test.shape

(38,)

## To Scale or Not To Scale

Scaling is a monotonic transformation 
* The relative order of smaller to larger value in a variable is maintained post the scaling

Vast majority of algorithms require scaling

Algorithms that do not require scaling:

> Algorithms that rely on rules 
* They would not be affected by any monotonic transformations of the variables
* e.g. CART, Random Forests, Gradient Boosted Decision Trees

> Algorithms that rely on distributions of the variables
* e.g. Naive Bayes

[Standardization and Normalization](https://stats.stackexchange.com/questions/10289/whats-the-difference-between-normalization-and-standardization) are ways to do scaling 

## Standardization

Transforms the features into a Standard Gaussian (or normal) distribution with a mean of 0 and standard deviation of 1

Used when algorithm requires computation of distance (Euclidean) to avoid large scale features dominating others 
* e.g. KNN, K-means, Minimum distance classifier

It matters in PCA to avoid bias towards high magnitude features 

For gradient descent based algorithm standardization helps in faster convergence

In SVM it can reduce the time to find support vectors

Scikit-learn implements data standardization in the StandardScaler module

In [7]:
# to do standardization
# recall standardization has mean 0, but can still have < -1 and > 1
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(X_train)
standardize_Xtrain = scaler.transform(X_train)

In [8]:
#recall data is shuffled
X_train[0:5,:]

array([[6.1, 2.9, 4.7, 1.4],
       [6. , 2.2, 4. , 1. ],
       [6.7, 3.1, 4.4, 1.4],
       [6.9, 3.1, 5.4, 2.1],
       [5.7, 2.6, 3.5, 1. ]])

In [9]:
standardize_Xtrain[0:5,:]

array([[ 0.34791671, -0.40297225,  0.57605563,  0.32985562],
       [ 0.22838704, -2.07456085,  0.17779495, -0.20171027],
       [ 1.06509472,  0.07462449,  0.40537248,  0.32985562],
       [ 1.30415405,  0.07462449,  0.97431631,  1.26009593],
       [-0.13020196, -1.11936736, -0.10667697, -0.20171027]])

## Exercise

Standardize X_test and print how first 5 rows of X_test and standardize_Xtest look like

In [10]:
# Standardize X_test

# recall that scaler was fit to X_train, so no need to re-fit the test 
# (don't know what the test data is, so need to use what X_train was)
standardize_X_test = scaler.transform(X_test)

X_test[0:5,:]

array([[5. , 3.5, 1.3, 0.3],
       [6.2, 2.9, 4.3, 1.3],
       [6.3, 2.5, 5. , 1.9],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 4. , 1.2, 0.2]])

In [11]:
standardize_X_test[0:5,:]

array([[-0.96690963,  1.02981797, -1.3583534 , -1.13195058],
       [ 0.46744638, -0.40297225,  0.3484781 ,  0.19696415],
       [ 0.58697605, -1.35816573,  0.74673878,  0.99431299],
       [ 1.30415405,  0.07462449,  0.80363316,  1.52587888],
       [-0.01067229,  2.22380983, -1.41524778, -1.26484206]])

## Normalization

Normalization transforms the features in the dataset so that it has a unit norm or has magnitude or length of 1 

The length of a vector is the square-root of the sum of squares of the vector elements 

A unit vector (or unit norm) is obtained by dividing the vector by its length 

Note: Normalizing the dataset is particularly useful in scenarios where the dataset is sparse (i.e., a large number of observations are zeros) and also have differing scales 

Normalization in Scikit-learn is implemented in the Normalizer module

In [12]:
from sklearn.preprocessing import Normalizer
scaler = Normalizer().fit(X_train)
normalize_Xtrain = scaler.transform(X_train)

In [13]:
X_train[0:5,:]

array([[6.1, 2.9, 4.7, 1.4],
       [6. , 2.2, 4. , 1. ],
       [6.7, 3.1, 4.4, 1.4],
       [6.9, 3.1, 5.4, 2.1],
       [5.7, 2.6, 3.5, 1. ]])

In [14]:
normalize_Xtrain[0:5,:]

array([[0.73081412, 0.34743622, 0.56308629, 0.16772783],
       [0.78892752, 0.28927343, 0.52595168, 0.13148792],
       [0.76945444, 0.35601624, 0.50531337, 0.16078153],
       [0.72415258, 0.32534391, 0.56672811, 0.22039426],
       [0.78667474, 0.35883409, 0.48304589, 0.13801311]])

## Exercise

Normalize X_test and print how first 5 rows of X_test and normalize_Xtest look like

In [15]:
# Normalize X_test

# again, already fit with xtrain
normalize_X_test = scaler.transform(X_test)

In [16]:
X_test[0:5,:]

array([[5. , 3.5, 1.3, 0.3],
       [6.2, 2.9, 4.3, 1.3],
       [6.3, 2.5, 5. , 1.9],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 4. , 1.2, 0.2]])

In [17]:
normalize_X_test[0:5,:]

array([[0.80033301, 0.56023311, 0.20808658, 0.04801998],
       [0.75728103, 0.3542121 , 0.52521104, 0.15878473],
       [0.72965359, 0.28954508, 0.57909015, 0.22005426],
       [0.73337886, 0.32948905, 0.54206264, 0.24445962],
       [0.81120865, 0.55945424, 0.16783627, 0.02797271]])

# *** Recall only use Standardization OR Normalization, not both

if values are between 0 and 1, use normalization, if guassian dist with mean 0, use standardization

## Label Encoding or Encoding Categorical Variables

Encoding - converting non-numerical features with labels into a numerical representation

Encoding in Scikit-learn using LabelEncoder - for encoding labels as integers 

We have already seen how species were encoded in iris dataset:
* 0 = setosa, 1 = versicolor, 2 = virginica

In avocado dataset:
The `region_categories` and `type_categories variables` store the unique categories in the `region` and `type` column

In [18]:
import pandas as pd
avocado_path = 'avocado.csv' #please make sure avacado.csv is in the same directory as the iPython notebook
avocado_df = pd.read_csv(avocado_path,header=0)
avocado_df.drop('Unnamed: 0', axis=1, inplace=True)

region_categories = avocado_df['region'].unique()
type_categories = avocado_df['type'].unique()

print('Region categories are: \n',region_categories,'\n')
print('Type categories are: \n',type_categories,'\n')

Region categories are: 
 ['Albany' 'Atlanta' 'BaltimoreWashington' 'Boise' 'Boston'
 'BuffaloRochester' 'California' 'Charlotte' 'Chicago' 'CincinnatiDayton'
 'Columbus' 'DallasFtWorth' 'Denver' 'Detroit' 'GrandRapids' 'GreatLakes'
 'HarrisburgScranton' 'HartfordSpringfield' 'Houston' 'Indianapolis'
 'Jacksonville' 'LasVegas' 'LosAngeles' 'Louisville' 'MiamiFtLauderdale'
 'Midsouth' 'Nashville' 'NewOrleansMobile' 'NewYork' 'Northeast'
 'NorthernNewEngland' 'Orlando' 'Philadelphia' 'PhoenixTucson'
 'Pittsburgh' 'Plains' 'Portland' 'RaleighGreensboro' 'RichmondNorfolk'
 'Roanoke' 'Sacramento' 'SanDiego' 'SanFrancisco' 'Seattle'
 'SouthCarolina' 'SouthCentral' 'Southeast' 'Spokane' 'StLouis' 'Syracuse'
 'Tampa' 'TotalUS' 'West' 'WestTexNewMexico'] 

Type categories are: 
 ['conventional' 'organic'] 



In [19]:
from sklearn.preprocessing import LabelEncoder

region_encoder = LabelEncoder()
encoded_region_cats = region_encoder.fit_transform(region_categories)
print('The encoded region categories are:', encoded_region_cats)

The encoded region categories are: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53]


In [20]:
print('Before Encoding the region column was: \n', avocado_df['region'])
print('\n')

avocado_df['region'] = region_encoder.transform(avocado_df['region'])
print('After Encoding the region column is: \n', avocado_df['region'])


Before Encoding the region column was: 
 0                  Albany
1                  Albany
2                  Albany
3                  Albany
4                  Albany
5                  Albany
6                  Albany
7                  Albany
8                  Albany
9                  Albany
10                 Albany
11                 Albany
12                 Albany
13                 Albany
14                 Albany
15                 Albany
16                 Albany
17                 Albany
18                 Albany
19                 Albany
20                 Albany
21                 Albany
22                 Albany
23                 Albany
24                 Albany
25                 Albany
26                 Albany
27                 Albany
28                 Albany
29                 Albany
               ...       
18219             TotalUS
18220             TotalUS
18221             TotalUS
18222             TotalUS
18223             TotalUS
18224             Total

## Exercise

Encode type categories print the encoded type categories and print the column before and after encoding

In [21]:
# Encoded Type Categories
type_encoder = LabelEncoder()
encoded_type_cats = type_encoder.fit_transform(type_categories)
print('The encoded type categories are:', encoded_type_cats)

The encoded type categories are: [0 1]


In [22]:
# Print the column before, encode type categories
print('Before Encoding the type column was: \n', avocado_df['type'])
print('\n')

Before Encoding the type column was: 
 0        conventional
1        conventional
2        conventional
3        conventional
4        conventional
5        conventional
6        conventional
7        conventional
8        conventional
9        conventional
10       conventional
11       conventional
12       conventional
13       conventional
14       conventional
15       conventional
16       conventional
17       conventional
18       conventional
19       conventional
20       conventional
21       conventional
22       conventional
23       conventional
24       conventional
25       conventional
26       conventional
27       conventional
28       conventional
29       conventional
             ...     
18219         organic
18220         organic
18221         organic
18222         organic
18223         organic
18224         organic
18225         organic
18226         organic
18227         organic
18228         organic
18229         organic
18230         organic
18231         o

In [24]:
# Print the column after encoding
avocado_df['type'] = type_encoder.transform(avocado_df['type'])
print('After Encoding the type column is: \n', avocado_df['type'])


After Encoding the type column is: 
 0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
18219    1
18220    1
18221    1
18222    1
18223    1
18224    1
18225    1
18226    1
18227    1
18228    1
18229    1
18230    1
18231    1
18232    1
18233    1
18234    1
18235    1
18236    1
18237    1
18238    1
18239    1
18240    1
18241    1
18242    1
18243    1
18244    1
18245    1
18246    1
18247    1
18248    1
Name: type, Length: 18249, dtype: int64


## Input Missing Data

It is often the case that a dataset contains several missing observations 

Scikit-learn implements the Imputer module for completing missing values

In [25]:
# We will first make some holes in our data
avocado_path = 'avocado.csv' #please make sure avacado.csv is in the same directory as the iPython notebook
avocado_df = pd.read_csv(avocado_path,header=0)
avocado_df.drop('Unnamed: 0', axis=1, inplace=True)

import random
import numpy as np

avocado_df.drop(avocado_df.columns[[0, 9, 10, 11, 12]], axis = 1, inplace = True) 

np.random.seed(100)
mask = np.random.choice([True, False], size=avocado_df.shape)
#print (mask)

mask[mask.all(1),-1] = 0
#print (mask)

#print (avocado_df.mask(mask))

#def add_random_na(row):
#    vals = row.values
#    for _ in range(random.randint(0,len(vals)-2)):
#        i = random.randint(0,len(vals)-1)
#        vals[i] = np.nan
#    return vals

avocado_df.mask(mask).head()


AveragePrice  Total Volume     4046       4225   4770  Total Bags  \
0           NaN           NaN  1036.74   54454.85  48.16     8696.87   
1           NaN           NaN      NaN   44638.81    NaN         NaN   
2          0.93           NaN      NaN  109149.67    NaN     8145.35   
3           NaN      78992.15  1132.00   71976.41    NaN         NaN   
4           NaN      51039.60   941.48   43838.39  75.78     6183.95   

   Small Bags  Large Bags  
0         NaN         NaN  
1         NaN         NaN  
2         NaN         NaN  
3      5677.4         NaN  
4         NaN         NaN

In [26]:
avocado_df.mask(mask).tail()


AveragePrice  Total Volume     4046     4225    4770  Total Bags  \
18244          1.63      17074.83      NaN      NaN     NaN    13498.67   
18245          1.71           NaN  1191.70  3431.50     NaN         NaN   
18246          1.87           NaN      NaN      NaN  727.94     9394.11   
18247           NaN           NaN      NaN      NaN  727.01    10969.54   
18248           NaN           NaN  2894.77  2356.13     NaN         NaN   

       Small Bags  Large Bags  
18244    13066.82      431.85  
18245     8940.04      324.80  
18246     9351.80       42.31  
18247    10919.54         NaN  
18248    11988.14         NaN

In [27]:

from sklearn.impute import SimpleImputer 

# impute missing values - axix=0: impute along columns
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
print(imputer.fit_transform(avocado_df.mask(mask)))

[[1.40089245e+00 8.76004541e+05 1.03674000e+03 ... 8.69687000e+03
  1.78906158e+05 5.54393126e+04]
 [1.40089245e+00 8.76004541e+05 2.90554507e+05 ... 2.42302277e+05
  1.78906158e+05 5.54393126e+04]
 [9.30000000e-01 8.76004541e+05 2.90554507e+05 ... 8.14535000e+03
  1.78906158e+05 5.54393126e+04]
 ...
 [1.87000000e+00 8.76004541e+05 2.90554507e+05 ... 9.39411000e+03
  9.35180000e+03 4.23100000e+01]
 [1.40089245e+00 8.76004541e+05 2.90554507e+05 ... 1.09695400e+04
  1.09195400e+04 5.54393126e+04]
 [1.40089245e+00 8.76004541e+05 2.89477000e+03 ... 2.42302277e+05
  1.19881400e+04 5.54393126e+04]]
